# Macros for kernel
KERNEL_CC      = gcc
KERNEL_AR      = ar
KERNEL_LD      = ld
KERNEL_ASM     = nasm
KERNEL_STRIP   = strip
KERNEL_OBJDUMP = objdump
KERNEL_CFLAGS  = -ffreestanding -Werror -Wall -nostdlib -nostartfiles -nodefaultlibs -Iinclude -I../include
KERNEL_LIBS    = libgcc.a ../lib/libmeinos/*.o ../lib/stdlibc/*.o

# Macros for libraries
LIBS_CC      = gcc
LIBS_AR      = ar
LIBS_ASM     = nasm
LIBS_CFLAGS  = -ffreestanding -Wall -Werror -nostdlib -nostartfiles -nodefaultlibs -I../../include -I../../../include

# Macros for applications
GCC_TOOLCHAIN = /usr/meinos
APPS_CC            = $(GCC_TOOLCHAIN)/bin/i586-pc-meinos-gcc -fno-builtin
APPS_LD            = $(GCC_TOOLCHAIN)/bin/i586-pc-meinos-ld
APPS_STRIP         = $(GCC_TOOLCHAIN)/bin/i586-pc-meinos-strip
APPS_OBJDUMP       = $(GCC_TOOLCHAIN)/bin/i586-pc-meinos-objdump
