# Macros for development utilities
CC = gcc

# Macros for kernel
KERNEL_CC      = gcc
KERNEL_AR      = ar
KERNEL_LD      = ld
KERNEL_ASM     = nasm
KERNEL_OBJDUMP = objdump
KERNEL_CFLAGS  = -g -c -ffreestanding -Werror -Wall -nostdlib -nostartfiles -nodefaultlibs -Iinclude -I../include

# Macros for libraries
LIBS_CC      = gcc
LIBS_AR      = ar
LIBS_RANLIB  = ranlib
LIBS_ASM     = nasm
LIBS_CFLAGS  = -g -c -ffreestanding -nostdlib -nostartfiles -nodefaultlibs -I../../include -I../../../include

# Macros for applications
GCC_TOOLCHAIN = /usr/meinos
APPS_CC            = $(GCC_TOOLCHAIN)/bin/i586-pc-meinos-gcc -fno-builtin -Wall -Werror
APPS_LD            = $(GCC_TOOLCHAIN)/bin/i586-pc-meinos-ld
APPS_OBJDUMP       = $(GCC_TOOLCHAIN)/bin/i586-pc-meinos-objdump
